account/urls.py
from django.urls import path

from account.views import UserLoginView, UserLogoutView, profile, RegisterUser, RegisterDoneView, ChangeUserDataView, \
    ChangeUserPasswordView

from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, \
    PasswordResetCompleteView

from django.urls import reverse_lazy

app_name = 'account'

urlpatterns = [

    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
    path('password/change/', ChangeUserPasswordView.as_view(), name='change_user_password'),
    path('profile/change/', ChangeUserDataView.as_view(), name='change_user_data'),
    path('profile/', profile, name='profile'),
    path('register/done/', RegisterUser.as_view(), name='register'),
    path('register/', RegisterDoneView.as_view(), name='register_done'),
    path('password/reset_done/', PasswordResetDoneView.as_view(template_name='email_sent.html'),
         name='password_reset_done'),
    path('password_reset/',
         PasswordResetView.as_view(template_name='reset_password.html', subject_template_name='reset_subject.txt',
                                   email_template_name='reset_email.txt',
                                   success_url=reverse_lazy("account:password_reset_done")), name='reset_password'),

    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(template_name='confirm_password.html',
                                                                     success_url=reverse_lazy(
                                                                         "account:password_reset_complete")),
         name='password_reset_confirm'),
    path('reset/done/', PasswordResetCompleteView.as_view(template_name='password_confirmed.html'),
         name='password_reset_complete'),

]

blog/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from blog import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('account.urls')),
    path('', include('main.urls')),
    path('social/', include('social_django.urls', namespace='social')),
]

if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class BlogUser(AbstractUser):
    """Класс пользователя блога"""

    send_message = models.BooleanField(default=True,
                                       verbose_name='Получать сообщения на электронную почту о новых постах')
    image = models.ImageField(upload_to="media", default='python.jpeg')

account/forms.py
from django import forms


from django.contrib.auth import password_validation

from account.models import BlogUser
from django.core.exceptions import ValidationError


class RegistrationUserForm(forms.ModelForm):
    """Форма регистрации пользователя блога"""

    email = forms.EmailField(required=True, label="Электронная почта")
    password1 = forms.CharField(label='Пароль', widget=forms.PasswordInput,
                                help_text=password_validation.password_validators_help_text_html())
    password2 = forms.CharField(label='Пароль(повторно)', widget=forms.PasswordInput,
                                help_text='Введите тот же самый пароль еще раз для проверки')


    def clean_password1(self):
        password1 = self.cleaned_data['password1']
        if password1:
            password_validation.validate_password(password1)
        return password1


    def clean(self):
        super().clean()
        password1 = self.cleaned_data['password1']
        password2 = self.cleaned_data['password2']
        if password1 and password2 and password1 != password2:
            errors = {
                'password2': ValidationError(
                   'Пароли не совпадают', code='password_mismatch'
                )
            }
            raise ValidationError(errors)


    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        if commit:
            user.save()
        return user


    class Meta:
        model = BlogUser
        fields = ('username', 'email', 'password1', 'password2', 'send_message')

class ChangeUserDataForm(forms.ModelForm):
    """Форма изменения ранее сохраненных данных пользователя блога"""

    class Meta:
        model = BlogUser
        fields = ('username', 'email','first_name', 'last_name', 'send_message', 'image')

account/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import CreateView, TemplateView, UpdateView

from account.models import BlogUser

from account.forms import RegistrationUserForm, ChangeUserDataForm


class UserLoginView(LoginView):
    """Класс авторизации пользователя на сайте"""
    template_name = "login.html"


class UserLogoutView(LogoutView):
    """Класс для выхода пользователя с аккаунта"""
    template_name = "logout.html"


@login_required
def profile(request):
    """Функция для отображения профиля авторизованного пользователя"""
    return render(request, 'profile.html')


class RegisterUser(CreateView):
    """Класс, регистрирующий пользователя на сайте"""

    model = BlogUser
    form_class = RegistrationUserForm
    template_name = "register.html"
    success_url = reverse_lazy('account:login')


class RegisterDoneView(TemplateView):
    """Класс, выводящий сообщение при успешной регистрации пользователя на сайте"""
    template_name = 'register_done.html'


class ChangeUserDataView(UpdateView, LoginRequiredMixin):
    """Класс для изменения данных авторизованного пользователя"""
    model = BlogUser
    template_name = "change_user_data.html"
    form_class = ChangeUserDataForm
    success_url = reverse_lazy("account:profile")

    def setup(self, request, *args, **kwargs):
        self.user_id = request.user.pk
        return super().setup(request, *args, **kwargs)

    def get_object(self, queryset=None):
        if not queryset:
            queryset = self.get_queryset()
        return get_object_or_404(queryset, pk=self.user_id)


class ChangeUserPasswordView(PasswordChangeView, LoginRequiredMixin):
    """Класс для изменения пароля пользователя"""
    model = BlogUser
    template_name = "change_user_password.html"
    success_url = reverse_lazy("account:profile")

account/templates/change_user_data.html
{% extends "start_page.html" %}

{% block content %}

<h2>Смена данных пользователя {{ user.username }}</h2>
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Изменить">
</form>

{% endblock %}

account/templates/change_user_password.html
{% extends "start_page.html" %}

{% block content %}

<h2>Смена пароля пользователя {{ user.username }}</h2>
<form action="" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Изменить пароль">
</form>

{% endblock %}

account/templates/confirm_password.html
{% extends "start_page.html" %}

{% block content %}

<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Подтвердить">
</form>


{% endblock %}

account/templates/email_sent.html
{% extends "start_page.html" %}

{% block content %}

{{ title }}

{% endblock %}

account/templates/login.html
{% extends "start_page.html" %}

{% block content %}
<h2>Авторизация</h2>
{% if user.is_authenticated %}
<h3>Вы выполнили вход ранее.</h3>

{% else %}
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Войти">
</form>

{% endif %}

<div>
    <h2> Войти через соцсети:</h2>
    <a href="{% url 'social:begin' 'vk-oauth2' %}">ВК</a>
    <a href="{% url 'social:begin' 'mailru-oauth2' %}">MAIL.RU</a>
    <a href="{% url 'social:begin' 'facebook' %}">Facebook</a>
    <a href="">Google</a>
</div>
<br>
<br>

<a href="{% url 'account:reset_password' %}">Забыли пароль?</a>

<br>
<br>
<br>
<br>
<a href="{% url 'account:register' %}">Регистрация</a>

{% endblock %}

account/templates/logout.html
{% extends "start_page.html" %}

{% block content %}
<h2>Выход с сайта</h2>

Вы осуществили выход с сайта!

{% endblock %}

account/templates/password_confirmed.html
{% extends "start_page.html" %}

{% block content %}

{{ title }}

{% endblock %}

account/templates/profile.html
{% extends "start_page.html" %}

{% block content %}
<h2>Профиль</h2>

<h1>Текущие данные:</h1>
<div>
    <img src="{{ user.image.url }}" alt=""><br>
    Логин: {{ user.username }}<br>
    Электронная почта: {{ user.email }}<br>

    {% if not user.first_name %}
    Имя: Значение отсутствует <br>
    {% else %}
    Имя: {{ user.first_name }}<br>
    {% endif %}

    {% if not user.last_name %}
    Фамилия: Значение отсутствует<br>
    {% else %}
    Фамилия: {{ user.last_name }}<br>
    {% endif %}

    {% if user.send_message %}
    Получать уведомления о новых постах: ДА
    {% else %}
    Получать уведомления о новых постах: НЕТ
    {% endif %}
    <br>
    <br>
    <br>
    <br>


</div>

<a href="{% url 'account:change_user_data' %}">Изменить данные пользователя</a><br>
<a href="{% url 'account:change_user_password' %}">Изменить пароль</a>


{% endblock %}

account/templates/register.html
{% extends "start_page.html" %}

{% block content %}
<h2>Регистрация</h2>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Зарегистрироваться">
</form>


{% endblock %}

account/templates/register_done.html
{% extends "start_page.html" %}

{% block content %}

<h2>Успешная регистрация!</h2>

{% endblock %}

account/templates/reset_password.html
{% extends "start_page.html" %}

{% block content %}
<h2>Смена пароля</h2>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Отправить">
</form>


{% endblock %}>