account/urls.py
from django.urls import path

from account.views import UserLoginView, UserLogoutView, profile, RegisterUser, RegisterDoneView, ChangeUserDataView, \
    ChangeUserPasswordView

from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, \
    PasswordResetCompleteView

from django.urls import reverse_lazy

app_name = 'account'

urlpatterns = [

    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
    path('password/change/', ChangeUserPasswordView.as_view(), name='change_user_password'),
    path('profile/change/', ChangeUserDataView.as_view(), name='change_user_data'),
    path('profile/', profile, name='profile'),
    path('register/done/', RegisterUser.as_view(), name='register'),
    path('register/', RegisterDoneView.as_view(), name='register_done'),
    path('password/reset_done/', PasswordResetDoneView.as_view(template_name='email_sent.html'),
         name='password_reset_done'),
    path('password_reset/',
         PasswordResetView.as_view(template_name='reset_password.html', subject_template_name='reset_subject.txt',
                                   email_template_name='reset_email.txt',
                                   success_url=reverse_lazy("account:password_reset_done")), name='reset_password'),

    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(template_name='confirm_password.html',
                                                                     success_url=reverse_lazy(
                                                                         "account:password_reset_complete")),
         name='password_reset_confirm'),
    path('reset/done/', PasswordResetCompleteView.as_view(template_name='password_confirmed.html'),
         name='password_reset_complete'),

]

blog/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from blog import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('account.urls')),
    path('', include('main.urls')),
    path('social/', include('social_django.urls', namespace='social')),
]

if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path

from main.views import start_page, post_detail, category_post, answer_comment, \
    CategoriesList, PostsAllList, PostView, PostsByCategoryList, PostDetailedView, popular_posts, PopularPostsList, \
    SimilarRandomPosts

app_name = "main"

urlpatterns = [
    path('', start_page, name="start_page"),
    path('post_detail/<int:id>', post_detail, name="post_detail"),
    path('category_post/<int:category_id>', category_post, name="category_post"),
    path('popular_posts/', popular_posts, name="popular_posts"),
    path('answer_comment/<int:id>', answer_comment, name="answer_comment"),

    path('api/categories_list/', CategoriesList.as_view()),
    path('api/posts_list/', PostsAllList.as_view()),
    path('api/post/<int:pk>/', PostView.as_view()),
    path('api/category/<int:pk>/', PostsByCategoryList.as_view()),
    path('api/post_detailed/<int:pk>/', PostDetailedView.as_view()),
    path('api/popular_posts/', PopularPostsList.as_view()),
    path('api/similar_random_posts/<int:pk>/', SimilarRandomPosts.as_view()),
]

main/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse


class Category(models.Model):
    """Класс категорий статей"""
    title = models.CharField(max_length=200, verbose_name="Название")

    class Meta:
        ordering = ['title']
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.title


class Post(models.Model):
    """Класс статей"""
    category = models.ForeignKey('Category', on_delete=models.CASCADE, verbose_name="Категория")
    title = models.CharField(max_length=200, unique=True, verbose_name="Название")
    description = models.TextField(verbose_name="Содержание")
    briefdescription = models.CharField(max_length=400, verbose_name="Краткое содержание")
    created = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")
    updated = models.DateTimeField(auto_now=True, verbose_name="Дата обновления")
    image = models.ImageField(upload_to='images', verbose_name="Изображение")
    author = models.CharField(max_length=200, blank=True, verbose_name="Автор")
    likes = models.IntegerField(default=0, blank=True, verbose_name="Лайки")
    views = models.IntegerField(default=0, blank=True, verbose_name="Просмотры")

    class Meta:
        ordering = ['created']
        verbose_name = 'Статья'
        verbose_name_plural = 'Статьи'

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('main:post_detail', args=[self.id])


class PostAdditionalImage(models.Model):
    """Класс дополнительных изображений к статьям"""
    post = models.ForeignKey(Post, on_delete=models.CASCADE, verbose_name='Статья')
    image = models.ImageField(upload_to='images', blank=True, verbose_name='Изображение')

    class Meta:
        verbose_name = 'Дополнительное изображение'
        verbose_name_plural = 'Дополнительные изображения'


class Comment(models.Model):
    """Класс комментария к статье"""
    post = models.ForeignKey('Post', on_delete=models.CASCADE, verbose_name='Статья')
    date_created = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    text = models.TextField(verbose_name='Оставить свой комментарий')
    is_publish = models.BooleanField(default=False, verbose_name='Опубликовать')

    class Meta:
        ordering = ['-is_publish', 'date_created']
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

    def __str__(self):
        return self.text

class AnswerComment(models.Model):
    """Класс ответа на комментарий """
    comment = models.ForeignKey('Comment', on_delete=models.CASCADE, verbose_name='Комментарий')
    date_created = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    text = models.TextField(verbose_name='Ответ')
    is_publish = models.BooleanField(default=False, verbose_name='Опубликовать')

    class Meta:
        ordering = ['-is_publish', 'date_created']
        verbose_name = 'Ответ на комментарий'
        verbose_name_plural = 'Ответы на комментарий'

    def __str__(self):
        return self.text


class Emails(models.Model):
    """Класс для хранения электронных адресов пользователей, которые хотят получать уведомления о новых постах"""
    email = models.EmailField(blank=False, verbose_name='Электронная почта')

    class Meta:
        verbose_name = 'Адрес электронной почты'
        verbose_name_plural = 'Адреса электронной почты'

    def __str__(self):
        return self.email


class View(models.Model):
    post = models.ForeignKey('Post', on_delete=models.CASCADE, verbose_name='Статья')
    category = models.ForeignKey('Category', on_delete=models.CASCADE, verbose_name="Категория")
    user = models.CharField(max_length=200, verbose_name="Пользователь")
    created = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")

    class Meta:
        verbose_name = 'Просмотр'
        verbose_name_plural = 'Просмотры'

    def __str__(self):
        return "id: " + str(self.id)


class Like(models.Model):
    post = models.ForeignKey('Post', on_delete=models.CASCADE, verbose_name='Статья')
    category = models.ForeignKey('Category', on_delete=models.CASCADE, verbose_name="Категория")
    user = models.CharField(max_length=200, verbose_name="Пользователь")
    created = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")

    class Meta:
        verbose_name = 'Лайк'
        verbose_name_plural = 'Лайки'

    def __str__(self):
        return "id: " + str(self.id)

main/forms.py
from django import forms

from .models import Comment, Emails, AnswerComment


class CommentForm(forms.ModelForm):
    """Класс формы для ввода комментария """
    class Meta:
        model = Comment
        fields = ['text']

class AnswerCommentForm(forms.ModelForm):
    """Класс формы для ввода ответа на комментарий """
    class Meta:
        model = AnswerComment
        fields = ['text']

class EmailsForm(forms.ModelForm):

    """Класс для формы ввода электронного адреса"""

    email = forms.EmailField(required=True, label='Электронный адрес')

    class Meta:
        model = Emails
        fields = ['email']

main/views.py
import generics as generics
from django.core.mail import send_mail
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.shortcuts import render, redirect
# from rest_framework.views import APIView
from rest_framework import generics

from account.models import BlogUser
from .forms import CommentForm, EmailsForm, AnswerCommentForm
from .models import Category, Post, Comment, Emails, AnswerComment, View, Like
# from .serializers import CategoryModelSerializer, PostModelSerializer, CommentModelSerializer
# from rest_framework.decorators import api_view
# from rest_framework.response import Response
from .serializers import CategorySerializer, PostSerializer, PostsAllSerializer, CategoryDetailSerializer, \
    PostDetailedSerializer, SimilarRandomPostsSerializer


def start_page(request):
    """Функция вывода стартовой страницы"""

    categories = Category.objects.all()
    posts = Post.objects.all()
    form = EmailsForm()
    if request.method == 'POST':
        new_email = EmailsForm(request.POST)
        if new_email.is_valid():
            new_email.save()
            return render(request, 'start_page.html',
                          {'categories': categories, 'posts': posts, 'form': form, 'message': "Ваш email сохранен!"})
    context = {'categories': categories, 'posts': posts, 'form': form}
    return render(request, 'start_page.html', context)


def post_detail(request, id):
    """Фукция вывода детальной информации статьи"""
    categories = Category.objects.all()
    post_info = Post.objects.filter(id=id)
    post = post_info[0]
    post_additional_images = post.postadditionalimage_set.all()
    category_id = post.category_id
    user = request.environ['HTTP_COOKIE']

    'Показ 3-ёх случайных похожих статей'
    category_random_posts = Post.objects.filter(category_id=category_id).exclude(id=id).order_by('?')[:3]

    'Счётчик просмотров'
    if request.method == 'GET':
        view = View.objects.filter(post_id=id, user=user)
        if not view:
            view = View(post_id=id, category_id=category_id, user=user)
            view.save()
            post.views += 1
            post_info.update(views=post.views)

    form = CommentForm()
    comments = Comment.objects.filter(is_publish='True', post_id=id)
    answer_comments = AnswerComment.objects.filter(is_publish='True')

    if request.method == 'POST':
        'Счётчик лайков'
        if request.POST.get('Likes'):
            like = Like.objects.filter(post_id=id, user=user)
            if like:
                like.delete()
                post.likes -= 1
            else:
                like = Like(post_id=id, category_id=category_id, user=user)
                like.save()
                post.likes += 1
            post_info.update(likes=post.likes)
        else:
            comment = Comment(text=request.POST.get("text"), post_id=id)
            comment.save()
        return redirect(post.get_absolute_url())
    context = {'categories': categories, 'post': post, 'post_additional_images': post_additional_images, 'form': form,
               'comments': comments, 'answer_comments': answer_comments, 'category_random_posts': category_random_posts}
    return render(request, 'post_detail.html', context)


# import telebot
# bot = telebot.TeleBot('5344465413:AAGG8i1-QKfIoQTzfEjQVB8pb9YAxZVp9Mw')
# CHANNEL_NAME = '@https://t.me/+CJtzLP2spNk5YjIy'

@receiver(post_save, sender=Comment)
def send_bot_message(sender, **kwargs):
    """Сигнал об оставленном комментарии"""

    print("Оставили комментарий")
    # bot.send_message(CHANNEL_NAME, "Оставили комментарий")

    send_mail(
        'Оставили комментарий',
        'Вам оставили комментарий на БЛОГ ITECH http://127.0.0.1:8000/',
        'python.project2012@gmail.com',
        ['python.project2012@gmail.com'],
        fail_silently=False)
    print("Письмо отправлено с помощью сигнала - оставили комментарий")


@receiver(post_save, sender=Post)
def listen_to_posts(sender, **kwargs):
    """Сигнал для отправки уведомлений о выходе нового поста"""

    emails_form = Emails.objects.all()
    emails_register = BlogUser.objects.filter(send_message=True).exclude(is_superuser=True)
    a = []
    if emails_form:
        for e in emails_form:
            a.append(e.email)
    if emails_register:
        for e in emails_register:
            a.append(e.email)
    recipients = list(set(a))
    subject = 'Новый пост в БЛОГЕ компании ITEC'
    # html_message = render_to_string('message.html')
    # plain_message = strip_tags(html_message)
    plain_message = "Новый пост на сайте айтек"
    from_email = 'python.project2012@gmail.com'
    # send_mail(subject, plain_message, from_email, [to], html_message=html_message)
    send_mail(subject, plain_message, from_email, recipients)
    print("Рассылка уведомлений")


def answer_comment(request, id):
    """Функция ответа на комментарий"""

    form = AnswerCommentForm()
    comment = Comment.objects.get(id=id)
    if request.method == 'POST':
        answer_comment = AnswerComment(text=request.POST.get("text"), comment_id=id)
        answer_comment.save()
        comment = Comment.objects.get(id=answer_comment.comment_id)
        post = Post.objects.get(id=comment.post_id)
        return redirect(post.get_absolute_url())
    context = {'form': form, 'comment': comment}
    return render(request, "answer_comment.html", context)


@receiver(post_save, sender=AnswerComment)
def send_message_about_answer(sender, **kwargs):
    """Сигнал об оставленном ответе на комментарии"""

    print("Оставили ответ на комментарий")
    send_mail(
        'Оставили ответ на комментарий',
        'Вам оставили ответ на комментарий на БЛОГ ITECH http://127.0.0.1:8000/',
        'python.project2012@gmail.com',
        ['python.project2012@gmail.com'],
        fail_silently=False)
    print("Письмо отправлено с помощью сигнала - ответ на комментарий")


def category_post(request, category_id):
    categories = Category.objects.all()
    posts = Post.objects.filter(category_id=category_id)
    context = {'categories': categories, 'posts': posts}
    return render(request, "category_post.html", context)


def popular_posts(request):
    categories = Category.objects.all()
    posts = Post.objects.all().order_by('-views', '-likes')
    context = {'categories': categories, 'posts': posts}
    return render(request, "popular_posts.html", context)


###### REST API ##########

class CategoriesList(generics.ListAPIView):
    """вывод всех категорий на главной странице"""
    queryset = Category.objects.all()
    serializer_class = CategorySerializer


class PostsAllList(generics.ListAPIView):
    """список всех постов на главной странице"""
    queryset = Post.objects.all()
    serializer_class = PostsAllSerializer


class PostView(generics.RetrieveAPIView):
    """информация о посте без комментариев и лайков"""
    queryset = Post.objects.all()
    serializer_class = PostSerializer


class PostsByCategoryList(generics.RetrieveAPIView):
    """все посты конкретной категории"""
    queryset = Category.objects.all()
    serializer_class = CategoryDetailSerializer


class PostDetailedView(generics.RetrieveAPIView):
    """пост с комментариями и ответами на комментарий"""
    queryset = Post.objects.all()
    serializer_class = PostDetailedSerializer


class PopularPostsList(generics.ListAPIView):
    """список популярных постов"""
    queryset = Post.objects.all().order_by('-views', '-likes')
    serializer_class = PostsAllSerializer


class SimilarRandomPosts(generics.RetrieveAPIView):
    """пост с 3-мя случайными похожими постами"""
    queryset = Post.objects.all()
    serializer_class = SimilarRandomPostsSerializer

main/templates/answer_comment.html
{% extends "start_page.html" %}
{% load static %}

{% block content %}
<script type="text/javascript" src="{% static 'scripts.js' %}"></script>

<p><h3> Оставьте здесь Ваш ответ на:</h3></p>
    <p><h4>Комментарий: {{ comment.text }}</h4></p>
        <p>{{ comment.date_created }}</p>

    <form action="" method="post" name="comment_form" onsubmit="return validate_comment_form ( )">
        {% csrf_token %}
        {{ form.as_p }}
        <button>Отправить</button>
    </form>

{% endblock %}

main/templates/category_post.html
{% extends "start_page.html" %}

{% block content %}
{% for post in posts %}
<div style="display: inline-block; justify-content: flex-start;">
    <a href="{{ post.get_absolute_url }}" style="text-decoration: none; color: black">
        <div style="width: 300px; height: 300px; margin: 20px; background: darkkhaki;">
            <div style="width:300px; height:150px;">
                {% if post.image %}
                <img src="{{ post.image.url }}" alt="" style="width:300px; height:150px">
                {% endif %}
            </div>
            <p style="margin: 15px;">{{ post.title }}</p>
            <p style="margin: 15px;">{{ post.briefdescription }}</p>
            <p style="margin: 15px;">Likes: {{ post.likes }}</p>
            <p style="margin: 15px;">Views: {{ post.views }}</p>
        </div>
    </a>
</div>
{% endfor %}
{% endblock %}

main/templates/change_user_data.html
{% extends "start_page.html" %}

{% block content %}

<h2>Смена данных пользователя {{ user.username }}</h2>
<form action="" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Изменить">
</form>

{% endblock %}

main/templates/popular_posts.html
{% extends "start_page.html" %}

{% block content %}
{% for post in posts %}
<div style="display: inline-block; justify-content: flex-start;">
    <a href="{{ post.get_absolute_url }}" style="text-decoration: none; color: black">
        <div style="width: 300px; height: 300px; margin: 20px; background: darkkhaki;">
            <div style="width:300px; height:150px;">
                {% if post.image %}
                <img src="{{ post.image.url }}" alt="" style="width:300px; height:150px">
                {% endif %}
            </div>
            <p style="margin: 15px;">{{ post.title }}</p>
            <p style="margin: 15px;">{{ post.briefdescription }}</p>
            <p style="margin: 15px;">Likes: {{ post.likes }}</p>
            <p style="margin: 15px;">Views: {{ post.views }}</p>
        </div>
    </a>
</div>
{% endfor %}
{% endblock %}

main/templates/post_detail.html
{% extends "start_page.html" %}
{% load static %}

{% block content %}
    <script type="text/javascript" src="{% static 'scripts.js' %}"></script>

    <div style="width: 300px; height: 300px; margin: 20px; background: darkkhaki;">
        <div style="width:300px; height:150px;">
            {% if post.image %}
            <img src="{{ post.image.url }}" style="width:300px; height:150px">
            {% endif %}
        </div>
        <p style="margin: 15px;">{{ post.title }}</p>
        <p style="margin: 15px;">{{ post.description }}</p>
        <form action="" method="POST" style="margin: 15px;">
            {% csrf_token %}
            <input type="submit" value="Likes" name="Likes"/> {{ post.likes }}
        </form>
        <p style="margin: 15px;">Views: {{ post.views }}</p>
    </div>
    <div style="margin: 20px;">
        {% if post_additional_images %}
            {% for additional_image in post_additional_images %}
                <img src="{{ additional_image.image.url }}" style="width:300px; height:150px">
            {% endfor %}
        {% endif %}
    </div>

<div style="margin: 20px;">
    {% for comment in comments %}
        <div style=" width: 300px; background: slategrey;">
            <p><h4>Комментарий: {{ comment.text }}</h4></p>
            <p>{{ comment.date_created }}</p>
        </div>
            <p><h5><a href="{% url 'main:answer_comment' comment.id %}">Ответить на комментарий </a></h5></p>
        {% for answer_comment in answer_comments %}
            {% if answer_comment.comment_id == comment.id %}
                <p><h4>Ответ: {{ answer_comment.text }}</h4></p>
                <p>{{ answer_comment.date_created }}</p>
            {% endif %}
        {% endfor %}

    {% endfor %}

        <form action="" method="post" name="comment_form" onsubmit="return validate_comment_form ( )">
            {% csrf_token %}
            {{ form.as_p }}
            <button>Отправить</button>
        </form>

</div>

    {% if category_random_posts %}
    <p style="margin: 15px;">Похожие статьи:</p>
    {% for post in category_random_posts %}
    <div style="display: inline-block; justify-content: flex-start;">
        <a href="{{ post.get_absolute_url }}" style="text-decoration: none; color: black">
            <div class="item_card" style="width: 300px; height: 300px; margin: 20px; background: darkkhaki;">
                <div style="width:300px; height:150px;">
                    {% if post.image %}
                    <img src="{{ post.image.url }}" alt="" style="width:300px; height:150px">
                    {% endif %}
                </div>
                <p style="margin: 15px;">{{ post.title }}</p>
                <p style="margin: 15px;">{{ post.briefdescription }}</p>
                <p style="margin: 15px;">Likes: {{ post.likes }}</p>
                <p style="margin: 15px;">Views: {{ post.views }}</p>
            </div>
        </a>
    </div>
    {% endfor %}
    {% endif %}
{% endblock %}

main/templates/start_page.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>

    <link rel="stylesheet" href="{% static 'css/start_page.css' %}">
</head>

<body>

<main>
    <div style="display: flex; justify-content:flex-start; background-color: grey">
        <a style="padding:15px; text-decoration: none; color:black">БЛОГ ITEC</a>

    </div>
    {% if user.is_authenticated %}
    <div style="padding-left: 1600px">
        <a  href="{% url 'account:profile' %}">{{ user.username }}<img style='width:50px; border-radius:30px'  src="{{ user.image.url }}" alt=""></a>
        <a href="{% url 'account:logout' %}">Выйти</a>
    </div>
    {% else %}
    <div>
        <a href="{% url 'account:login' %}">Войти</a>
        <a href="{% url 'account:register' %}">Регистрация</a>
    </div>
    {% endif %}

    <div style="display: flex; justify-content:flex-start; background-color: bisque">
        <a href="{% url 'main:start_page' %}" style="padding:15px; text-decoration: none; color:black">Главная</a>
        <a href="{% url 'main:popular_posts' %}" style="padding:15px; text-decoration: none; color:black">Популярное</a>
        {% for category in categories %}
        <a href="{% url 'main:category_post' category.id %}" style="padding:15px; text-decoration: none; color:black">{{ category.title }}</a>
        {% endfor %}
    </div>

    {% block content %}
    {% for post in posts %}
    <div style="display: inline-block; justify-content: flex-start;">
        <a href="{{ post.get_absolute_url }}" style="text-decoration: none; color: black">
            <div style="width: 300px; height: 300px; margin: 20px; background: darkkhaki;">
                <div style="width:300px; height:150px;">
                    {% if post.image %}
                    <img src="{{ post.image.url }}" alt="" style="width:300px; height:150px">
                    {% endif %}
                </div>
                <p style="margin: 15px;">{{ post.title }}</p>
                <p style="margin: 15px;">{{ post.briefdescription }}</p>
                <p style="margin: 15px;">Likes: {{ post.likes }}</p>
                <p style="margin: 15px;">Views: {{ post.views }}</p>
            </div>
        </a>
    </div>
    {% endfor %}
    <div>
        <form style="background-color: grey" action="" method="POST">
            {% csrf_token %}
            <h3>Хочу получать уведомления о новых постах ITEC</h3>
            {{ form.as_p }}
            <button>Отправить</button>
        </form>
        <div>
            {{ message }}
        </div>
    </div>
    {% endblock %}
</main>

</body>
</html>